"""empty message

Revision ID: 3e414d1f3b0e
Revises: a8ca00f3981a
Create Date: 2017-09-01 13:54:51.872659

"""

# revision identifiers, used by Alembic.
revision = '3e414d1f3b0e'
down_revision = 'a8ca00f3981a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
