"""empty message

Revision ID: 5566f41bc3ab
Revises: a01a162c8d56
Create Date: 2017-09-01 18:44:55.231471

"""

# revision identifiers, used by Alembic.
revision = '5566f41bc3ab'
down_revision = 'a01a162c8d56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
