"""empty message

Revision ID: 975809d06e1e
Revises: cd02fdd3a60b
Create Date: 2017-08-28 18:32:01.348570

"""

# revision identifiers, used by Alembic.
revision = '975809d06e1e'
down_revision = 'cd02fdd3a60b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
