"""empty message

Revision ID: 98c8c66734dc
Revises: 9d6a41549fc8
Create Date: 2017-11-07 19:21:07.821796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c8c66734dc'
down_revision = '9d6a41549fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_username', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author_username')
    # ### end Alembic commands ###
