"""empty message

Revision ID: a01a162c8d56
Revises: c271aaa2278d
Create Date: 2017-09-01 18:44:01.515020

"""

# revision identifiers, used by Alembic.
revision = 'a01a162c8d56'
down_revision = 'c271aaa2278d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
