"""empty message

Revision ID: c271aaa2278d
Revises: 3e414d1f3b0e
Create Date: 2017-09-01 13:55:08.374607

"""

# revision identifiers, used by Alembic.
revision = 'c271aaa2278d'
down_revision = '3e414d1f3b0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
